[server]
headless = true
enableCORS = true
enableXsrfProtection = true
address = "0.0.0.0"
port = 5000

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#7E57C2"  # Purple shade
backgroundColor = "#0E1117"  # Dark background
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"